import { SvgComponent } from '../typings';

export const ArrowDown: SvgComponent;
export const ArrowLeft: SvgComponent;
export const ArrowRight: SvgComponent;
export const ArrowUp: SvgComponent;
export const TrendingDown: SvgComponent;
export const TrendingUp: SvgComponent;
export const CornerDownLeft: SvgComponent;
export const CornerDownRight: SvgComponent;
export const CornerLeftDown: SvgComponent;
export const CornerRightDown: SvgComponent;
export const CornerRightUp: SvgComponent;
export const CornerUpLeft: SvgComponent;
export const RotateCCW: SvgComponent;
export const RotateCW: SvgComponent;
export const Repeat: SvgComponent;
export const RefreshCW: SvgComponent;
export const Minimize2: SvgComponent;
export const Maximize2: SvgComponent;
export const CornerLeftUp: SvgComponent;
export const CornerUpRight: SvgComponent;
