import { SvgComponent } from '../typings';

export const Briefcase: SvgComponent;
export const Feather: SvgComponent;
export const Grid: SvgComponent;
export const Hammer: SvgComponent;
export const Layout: SvgComponent;
export const Lock: SvgComponent;
export const Map: SvgComponent;
export const MinusCircle: SvgComponent;
export const MinusSquare: SvgComponent;
export const Navigation: SvgComponent;
export const Navigation2: SvgComponent;
export const Paperclip: SvgComponent;
export const Phone: SvgComponent;
export const PlusCircle: SvgComponent;
export const Scissors: SvgComponent;
export const Sidebar: SvgComponent;
export const ToggleLeft: SvgComponent;
export const ToggleRight: SvgComponent;
export const Tool: SvgComponent;
export const Unlock: SvgComponent;
export const XCircle: SvgComponent;
export const ZoomIn: SvgComponent;
export const ZoomOut: SvgComponent;
